const insightsAnchor=document.querySelector('#progress .history-title');
const insightsSection=document.createElement('section');insightsSection.className='smart-insights';insightsSection.innerHTML='<div class="section-title"><div><span>THIS WEEK</span><h2>What the data says</h2></div></div><div class="insight-grid" id="insight-grid"></div>';
insightsAnchor.before(insightsSection);
const daysAgo=days=>Date.now()-days*86400000;
function changeText(value,unit){if(value===null)return'Not enough data';if(Math.abs(value)<.05)return`Stable ${unit}`;return`${value>0?'↑':'↓'} ${Math.abs(value).toFixed(1)} ${unit}`}
function weeklyIntakes(){const values=[];for(let offset=0;offset<7;offset++){const day=new Date();day.setDate(day.getDate()-offset);const intake=readLocal(`form-daily-intake-${localDateId(day)}`,null);if(intake)values.push(Number(intake.calories)||0)}return values}
function estimateGoal(checkins,goal){if(checkins.length<2)return{value:'Collecting data',note:'Two or more check-ins are needed for a responsible estimate.'};const first=checkins[0],last=checkins[checkins.length-1],days=Math.max(1,(last.date-first.date)/86400000);let remaining,rate,label;if(goal==='lose'){const target=last.sex==='female'?28:20;remaining=last.bodyFat-target;rate=(first.bodyFat-last.bodyFat)/days;label=`about ${target}% body fat`}else if(goal==='gain'){const target=first.weight*1.08;remaining=target-last.weight;rate=(last.weight-first.weight)/days;label=`about ${target.toFixed(1)} kg`}else{const target=first.leanMass+3;remaining=target-last.leanMass;rate=(last.leanMass-first.leanMass)/days;label=`about ${target.toFixed(1)} kg lean mass`}if(remaining<=0)return{value:'Goal range reached',note:`Your current estimate is already within the program target of ${label}.`};if(rate<=0)return{value:'No date yet',note:'The recent trend is not moving toward the program target yet.'};const goalDays=Math.ceil(remaining/rate);if(goalDays>730)return{value:'Over 2 years',note:'The current rate is too slow for a useful short-term estimate.'};const date=new Date();date.setDate(date.getDate()+goalDays);return{value:date.toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'}),note:`Projection toward ${label}, based on your measured rate—not a guarantee.`}}
function renderInsights(){const checkins=readLocal('form-body-checkins',[]).filter(x=>Number(x.date)).sort((a,b)=>a.date-b.date),latest=checkins.at(-1),prior=checkins.filter(x=>x.date<=daysAgo(6)).at(-1);const weightChange=latest&&prior?latest.weight-prior.weight:null,waistChange=latest&&prior?latest.waist-prior.waist:null;const sets=readLocal('form-workout-history',[]),recentSets=sets.filter(x=>x.date>=daysAgo(7)),olderSets=sets.filter(x=>x.date>=daysAgo(14)&&x.date<daysAgo(7));const best=items=>items.reduce((top,x)=>Math.max(top,(Number(x.weight)||0)*(1+(Number(x.reps)||0)/30)||Number(x.reps)||0),0),recentBest=best(recentSets),olderBest=best(olderSets),strength=olderBest?((recentBest-olderBest)/olderBest*100):null;const completions=readLocal('form-exercise-completions',[]).filter(x=>x.date>=daysAgo(7)),workoutDays=new Set(completions.map(x=>localDateId(x.date))).size,setup=readLocal('form-onboarding',{}),targetDays=Number(setup.days)||4,consistency=Math.min(100,Math.round(workoutDays/targetDays*100));const calories=weeklyIntakes(),average=calories.length?Math.round(calories.reduce((a,b)=>a+b,0)/calories.length):null,goal=readLocal('form-training-goal','muscle'),projection=estimateGoal(checkins,goal);const cards=[['ESTIMATED GOAL DATE',projection.value,projection.note],['WEIGHT TREND',changeText(weightChange,'kg'),weightChange===null?'Add another check-in at least one week apart.':`Compared with your latest check-in from at least six days earlier.`],['WAIST CHANGE',changeText(waistChange,'cm'),waistChange===null?'Waist measurements from two check-ins are needed.':'Measured change; daily fluctuations are normal.'],['STRENGTH',strength===null?'Building baseline':`${strength>=0?'+':''}${strength.toFixed(1)}%`,strength===null?'Log sets across two weeks to compare performance.':'Estimated from your strongest logged sets versus last week.'],['CONSISTENCY',`${workoutDays} / ${targetDays} days`,`${consistency}% of your planned weekly training frequency.`],['AVG CALORIES',average===null?'No meals logged':`${average.toLocaleString()} kcal`,average===null?'Log meals to unlock a seven-day average.':`Average across ${calories.length} logged day${calories.length===1?'':'s'} this week.`]];document.getElementById('insight-grid').innerHTML=cards.map(([label,value,note],i)=>`<article class="insight-card"><span>${label}</span><strong class="${i===0||String(value).startsWith('+')?'positive':''}">${value}</strong><p>${note}</p></article>`).join('')}
window.addEventListener('localDataChanged',renderInsights);window.addEventListener('exerciseCompleted',renderInsights);renderInsights();
