const defaultReminders={workout:{enabled:false,time:'18:00'},meal:{enabled:false,time:'12:30'},water:{enabled:false,hours:2},weigh:{enabled:false,time:'08:00'},photo:{enabled:false,time:'09:00'}};
let reminderSettings={...defaultReminders,...readLocal('form-reminders',{})};Object.keys(defaultReminders).forEach(key=>reminderSettings[key]={...defaultReminders[key],...(reminderSettings[key]||{})});
const notificationList=document.querySelector('#notifications .notification-list'),reminderButton=document.createElement('button');reminderButton.className='reminder-settings-button';reminderButton.innerHTML='<span>Configure reminders</span><b>Schedule →</b>';notificationList.before(reminderButton);
const reminderSheet=document.createElement('div');reminderSheet.className='sheet';reminderSheet.id='reminder-settings';reminderSheet.setAttribute('aria-hidden','true');reminderSheet.innerHTML=`<div class="sheet-content reminder-content"><button class="close" type="button">×</button><p class="eyebrow">GENTLE NUDGES</p><h2>Remember what<br><em>matters to you.</em></h2><p class="muted">Choose only the reminders that feel useful.</p><form id="reminder-form"><div class="reminder-list">${[['workout','Workout','Training time'],['meal','Meal','Meal check-in'],['weigh','Weigh-in','Weekly measurement'],['photo','Progress photo','Monthly photo']].map(([key,title,note])=>`<label class="reminder-row"><input type="checkbox" name="${key}-enabled"><span><b>${title}</b><small>${note}</small></span><input type="time" name="${key}-time"></label>`).join('')}<label class="reminder-row water"><input type="checkbox" name="water-enabled"><span><b>Water</b><small>Between 08:00 and 22:00</small></span><select name="water-hours"><option value="1">Every hour</option><option value="2">Every 2h</option><option value="3">Every 3h</option><option value="4">Every 4h</option></select></label></div><p class="reminder-permission">Browser notifications work on localhost and HTTPS. On iPhone, install the site to the Home Screen and allow notifications. While this prototype is not installed, keep the app open for reliable reminders.</p><button class="primary" type="submit">Save reminders</button></form></div>`;document.querySelector('.phone-shell').appendChild(reminderSheet);
function fillReminders(){const form=document.getElementById('reminder-form');['workout','meal','weigh','photo'].forEach(key=>{form.elements[`${key}-enabled`].checked=reminderSettings[key].enabled;form.elements[`${key}-time`].value=reminderSettings[key].time});form.elements['water-enabled'].checked=reminderSettings.water.enabled;form.elements['water-hours'].value=reminderSettings.water.hours}
function reminderMessage(type){return{workout:['Workout time','Your planned session is ready when you are.'],meal:['Meal check-in','A quick meal log keeps today’s macros useful.'],water:['Water check','A glass of water would fit nicely here.'],weigh:['Weekly weigh-in','Use the same conditions for a cleaner trend.'],photo:['Progress photo','A consistent monthly photo can reveal quiet progress.']}[type]}
function deliverReminder(type,id){const sent=readLocal('form-reminders-sent',{});if(sent[id])return;sent[id]=Date.now();writeLocal('form-reminders-sent',sent);const[title,body]=reminderMessage(type);homeToast(title);if('Notification'in window&&Notification.permission==='granted')new Notification(title,{body,tag:id});const article=document.createElement('article');article.className='notification unread';article.innerHTML=`<i>◉</i><div><strong>${title}</strong><p>${body}</p><small>JUST NOW</small></div>`;notificationList.prepend(article)}
function checkReminders(){const now=new Date(),today=localDateId(now),minutes=now.getHours()*60+now.getMinutes();['workout','meal','weigh','photo'].forEach(type=>{const item=reminderSettings[type];if(!item.enabled)return;const[h,m]=item.time.split(':').map(Number),due=h*60+m;const frequencyOk=type==='weigh'?now.getDay()===1:type==='photo'?now.getDate()===1:true;if(frequencyOk&&minutes>=due&&minutes<due+2)deliverReminder(type,`${today}-${type}-${item.time}`)});if(reminderSettings.water.enabled&&now.getHours()>=8&&now.getHours()<=22&&now.getMinutes()<2&&(now.getHours()-8)%Number(reminderSettings.water.hours)===0)deliverReminder('water',`${today}-water-${now.getHours()}`)}
reminderButton.addEventListener('click',()=>{fillReminders();reminderSheet.classList.add('open');reminderSheet.setAttribute('aria-hidden','false')});reminderSheet.querySelector('.close').addEventListener('click',()=>{reminderSheet.classList.remove('open');reminderSheet.setAttribute('aria-hidden','true')});
document.getElementById('reminder-form').addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget;['workout','meal','weigh','photo'].forEach(key=>reminderSettings[key]={enabled:form.elements[`${key}-enabled`].checked,time:form.elements[`${key}-time`].value});reminderSettings.water={enabled:form.elements['water-enabled'].checked,hours:Number(form.elements['water-hours'].value)};if(Object.values(reminderSettings).some(item=>item.enabled)&&'Notification'in window&&Notification.permission==='default'){try{await Notification.requestPermission()}catch{}}writeLocal('form-reminders',reminderSettings);reminderSheet.classList.remove('open');reminderSheet.setAttribute('aria-hidden','true');homeToast('Reminder schedule saved.')});
fillReminders();checkReminders();setInterval(checkReminders,30000);
